# Generated by Django 4.2.7 on 2023-11-30 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketmaster', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=200)),
                ('eventLocation', models.CharField(max_length=200)),
                ('eventTime', models.CharField(max_length=200)),
                ('eventTicketURL', models.CharField(max_length=300)),
            ],
        ),
    ]
