# Generated by Django 4.2.7 on 2023-12-03 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketmaster', '0002_eventtable'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtable',
            name='eventDate',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='eventtable',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
