# Generated by Django 4.2.7 on 2023-12-05 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketmaster', '0004_alter_eventtable_eventtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtable',
            name='eventImage',
            field=models.CharField(default='N/A', max_length=400),
        ),
    ]
